// <auto-generated />
using System;
using AirLineMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirLineMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(AirLinceMetricsDbContext))]
    [Migration("20251227174001_EntitiesConfigurationsDone")]
    partial class EntitiesConfigurationsDone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.AirCraft", b =>
                {
                    b.Property<int>("AirCraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AIRCRAFT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirCraftId"));

                    b.Property<string>("AirCraftName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("NAME");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int")
                        .HasColumnName("CAPACITY");

                    b.HasKey("AirCraftId");

                    b.ToTable("AIRCRAFT", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AIRPORT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("STATE_ID");

                    b.HasKey("AirportId");

                    b.HasIndex("StateId");

                    b.ToTable("AIRPORTS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.BaggageReservation", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BAGGAGE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageId"));

                    b.Property<int>("BaggageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BAGGAGE_TYPE_ID");

                    b.Property<int>("FlightDetailId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_DETAIL_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("BaggageId");

                    b.HasIndex("BaggageTypeId");

                    b.HasIndex("FlightDetailId");

                    b.ToTable("BAGGAGES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.BaggageType", b =>
                {
                    b.Property<int>("BaggageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BAGGAGE_TYPE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageTypeId"));

                    b.Property<string>("BaggageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRIPTION");

                    b.HasKey("BaggageTypeId");

                    b.ToTable("BAGGAGE_TYPES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.CancellationReason", b =>
                {
                    b.Property<int>("CancellationReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CANCELLATION_REASSON_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationReasonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.HasKey("CancellationReasonId");

                    b.ToTable("CANCELLATION_REASSONS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COUNTRY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("COUNTRY_NAME");

                    b.HasKey("CountryId");

                    b.ToTable("COUNTRIES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("ActualArrival")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACTUAL_ARRIVAL");

                    b.Property<string>("ActualDeparture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACTUAL_DEPARTURE");

                    b.Property<int>("AirCraftId")
                        .HasColumnType("int")
                        .HasColumnName("AIRCRAFT_ID");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int")
                        .HasColumnName("DESTINATION_AIRPORT_ID");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FLIGHT_CODE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int")
                        .HasColumnName("ORIGINAL_AIRPORT_ID");

                    b.Property<string>("ScheduledArrival")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SCHEDULED_ARRIVAL");

                    b.Property<string>("ScheduledDeparture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SCHEDULED_DEPARTURE");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("STATE_ID");

                    b.HasKey("FlightId");

                    b.HasIndex("AirCraftId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("StateId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.FlightDetail", b =>
                {
                    b.Property<int>("FlightDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_DETAIL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightDetailId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit")
                        .HasColumnName("IS_CANCELLED");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PASSENGER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.HasKey("FlightDetailId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("FlightDetails");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.FlightPromotion", b =>
                {
                    b.Property<int>("FlightPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_PROMOTION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightPromotionId"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PROMOTION_ID");

                    b.HasKey("FlightPromotionId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PromotionId");

                    b.ToTable("FLIGHTS_PROMOTIONS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INVOICE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PASSENGER_ID");

                    b.HasKey("InvoiceId");

                    b.HasIndex("PassengerId");

                    b.ToTable("INVOICES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INVOICE_DETAIL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceDetailId"));

                    b.Property<int>("FlightDetailId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_DETAIL_ID");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("INVOICE_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.HasKey("InvoiceDetailId");

                    b.HasIndex("FlightDetailId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("INVOICE_DETAILS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.InvoicePayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("INVOICE_ID");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAYMENT_DATE");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_METHOD_ID");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("INVOICE_PAYMENTS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.OperationalCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OPERATIONAL_COST_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AirportFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("AIRPORT_FEES");

                    b.Property<decimal>("CrewCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CREW_COST");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FUEL_COST");

                    b.Property<decimal>("MaintenanceCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MAINTENANCE_COST");

                    b.Property<DateTime>("OperationalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OPERATIONAL_DATE");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("OPERATIONAL_COSTS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PASSENGER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DOCUMENT_TYPE_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int")
                        .HasColumnName("MOBILE_NUMBER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int>("PassengerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PASSENGER_TYPE_ID");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("STATE_ID");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("STREET");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SURNAME");

                    b.HasKey("PassengerId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("StateId");

                    b.ToTable("PASSENGERS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PassengerType", b =>
                {
                    b.Property<int>("PassengerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PASSENGER_TYPE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.HasKey("PassengerTypeId");

                    b.ToTable("PASSENGER_TYPES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_METHOD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PAYMENT_METHODS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PROMOTION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<double>("PromotionDiscount")
                        .HasColumnType("float")
                        .HasColumnName("PROMOTION_DISCOUNT");

                    b.Property<DateTime>("PromotionEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("END");

                    b.Property<DateTime>("PromotionStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("START");

                    b.HasKey("PromotionId");

                    b.ToTable("PROMOTIONS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PurchaseCancellation", b =>
                {
                    b.Property<int>("CancellationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CANCELLATION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationId"));

                    b.Property<DateTime>("CancellationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int>("CancellationReasonId")
                        .HasColumnType("int")
                        .HasColumnName("CANCELLATION_REASSON_ID");

                    b.Property<int>("InvoiceDetailId")
                        .HasColumnType("int")
                        .HasColumnName("INVOICE_DETAIL_ID");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("REFOUND_AMOUNT");

                    b.Property<int>("SatisfactionEstimated")
                        .HasColumnType("int")
                        .HasColumnName("SATISFACTION_ESTIMATED");

                    b.HasKey("CancellationId");

                    b.HasIndex("CancellationReasonId");

                    b.HasIndex("InvoiceDetailId");

                    b.ToTable("PURCHASE_CANCELLATIONS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.SeatReservation", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SEAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("FlighDetailtId")
                        .HasColumnType("int")
                        .HasColumnName("FLIGHT_DETAIL_ID");

                    b.Property<bool>("IsBussy")
                        .HasColumnType("bit")
                        .HasColumnName("IS_BUSY");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("SEAT_NUMBER");

                    b.Property<int>("SeatTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SEAT_TYPE_ID");

                    b.HasKey("SeatId");

                    b.HasIndex("FlighDetailtId");

                    b.HasIndex("SeatTypeId");

                    b.ToTable("SEATS", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.SeatType", b =>
                {
                    b.Property<int>("SeatTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SEAT_TYPE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatTypeId"));

                    b.Property<double>("AddedSeatTypePrice")
                        .HasColumnType("float")
                        .HasColumnName("ADDED_SEAT_TYPE_PRICE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("SeatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SEAT_NAME");

                    b.HasKey("SeatTypeId");

                    b.ToTable("SEAT_TYPES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STATE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("COUNTRY_ID");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATE_NAME");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("STATES", (string)null);
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Airport", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.State", "StateNavigation")
                        .WithMany("AiportsNavigation")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AIRPORTS_STATES");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.BaggageReservation", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.BaggageType", "BaggageTypeNavigation")
                        .WithMany("BaggageReservationNavigation")
                        .HasForeignKey("BaggageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BAGGAGE_BAGGAGE_TYPE");

                    b.HasOne("AirLineMetrics.Domain.Entities.FlightDetail", "FlightDetailNavigation")
                        .WithMany("BaggageReservationNavigation")
                        .HasForeignKey("FlightDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BAGGAGE_FLIGHT_DETAILS");

                    b.Navigation("BaggageTypeNavigation");

                    b.Navigation("FlightDetailNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Flight", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.AirCraft", "AirCraftNavigation")
                        .WithMany("FlightsNavigation")
                        .HasForeignKey("AirCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_AIRCRAFTS");

                    b.HasOne("AirLineMetrics.Domain.Entities.Airport", "DestinationAirportNavigation")
                        .WithMany("DestinationFlightNavigation")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_AIRPORTS_DESTINATION");

                    b.HasOne("AirLineMetrics.Domain.Entities.Airport", "OriginAirportNavigation")
                        .WithMany("OriginFlightNavigation")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_AIRPORTS_ORIGIN");

                    b.HasOne("AirLineMetrics.Domain.Entities.State", "StateNavigation")
                        .WithMany("FlightNavigation")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_STATES");

                    b.Navigation("AirCraftNavigation");

                    b.Navigation("DestinationAirportNavigation");

                    b.Navigation("OriginAirportNavigation");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.FlightDetail", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Flight", "FlightNavigation")
                        .WithMany("FlightDetailsNavigation")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_DETAILS_FLIGTHS");

                    b.HasOne("AirLineMetrics.Domain.Entities.Passenger", "PassengerNavigation")
                        .WithMany("FlightDetailsNavigation")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_DETAILS_PASSENGERS");

                    b.Navigation("FlightNavigation");

                    b.Navigation("PassengerNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.FlightPromotion", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Flight", "FlightNavigation")
                        .WithMany("FlightPromotionsNavigation")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_PROMOTIONS_FLIGHTS");

                    b.HasOne("AirLineMetrics.Domain.Entities.Promotion", "PromotionNavigation")
                        .WithMany("FlightPromotionsNavigation")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_PROMOTIONS_PROMOTIONS");

                    b.Navigation("FlightNavigation");

                    b.Navigation("PromotionNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Passenger", "PassengerNavigation")
                        .WithMany("InvoiceNavigation")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICES_PASSENGERS");

                    b.Navigation("PassengerNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.FlightDetail", "FlightDetailNavigation")
                        .WithMany("InvoiceDetailNavigation")
                        .HasForeignKey("FlightDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_DETAILS_FLIGHT_DETAILS");

                    b.HasOne("AirLineMetrics.Domain.Entities.Invoice", "InvoiceNavigation")
                        .WithMany("InvoiceDetailNavigation")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_DETAILS_INVOICES");

                    b.Navigation("FlightDetailNavigation");

                    b.Navigation("InvoiceNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.InvoicePayment", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Invoice", "InvoiceNavigation")
                        .WithMany("InvoicePaymentNavigation")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_PAYMENT_INVOICE_ID");

                    b.HasOne("AirLineMetrics.Domain.Entities.PaymentMethod", "PaymentMethodNavigation")
                        .WithMany("InvoicePaymentNavigation")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INVOICE_PAYMENT_PAYMENTE_METHOD_ID");

                    b.Navigation("InvoiceNavigation");

                    b.Navigation("PaymentMethodNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.OperationalCost", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Flight", "FlightNavigation")
                        .WithMany("OperationalCostsNavigation")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OPERATIONAL_COSTS_FLIGHTS");

                    b.Navigation("FlightNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Passenger", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.DocumentType", "DocumentTypeNavigation")
                        .WithMany("PassengerNavigation")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PASSENGERS_DOCUMENT_TYPES");

                    b.HasOne("AirLineMetrics.Domain.Entities.PassengerType", "PassengerTypeNavigation")
                        .WithMany("PassengersNavigation")
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PASSENGERS_PASSENGER_TYPES");

                    b.HasOne("AirLineMetrics.Domain.Entities.State", "StateNavigation")
                        .WithMany("PassengersNavigation")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PASSENGERS_STATES");

                    b.Navigation("DocumentTypeNavigation");

                    b.Navigation("PassengerTypeNavigation");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PurchaseCancellation", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.CancellationReason", "CancellationReasonNavigation")
                        .WithMany("PurchaseCancellationNavigation")
                        .HasForeignKey("CancellationReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PURCHASE_CANCELLATIONS_CANCELLATION_REASONS");

                    b.HasOne("AirLineMetrics.Domain.Entities.InvoiceDetail", "InvoiceDetailNavigation")
                        .WithMany("PurchaseCancellationNavigation")
                        .HasForeignKey("InvoiceDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PURCHASE_CANCELLATIONS_INVOICE_DETAILS");

                    b.Navigation("CancellationReasonNavigation");

                    b.Navigation("InvoiceDetailNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.SeatReservation", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.FlightDetail", "FlightDetailNavigation")
                        .WithMany("SeatReservationNavigation")
                        .HasForeignKey("FlighDetailtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SEAT_RESERVATIONS_FLIGHT_DETAILS");

                    b.HasOne("AirLineMetrics.Domain.Entities.SeatType", "SeatTypeNavigation")
                        .WithMany("SeatReservationNavigation")
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SEAT_RESERVATIONS_SEAT_TYPES");

                    b.Navigation("FlightDetailNavigation");

                    b.Navigation("SeatTypeNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.State", b =>
                {
                    b.HasOne("AirLineMetrics.Domain.Entities.Country", "CountryNavigation")
                        .WithMany("StateNavigation")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STATES_COUNTRIES");

                    b.Navigation("CountryNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.AirCraft", b =>
                {
                    b.Navigation("FlightsNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Airport", b =>
                {
                    b.Navigation("DestinationFlightNavigation");

                    b.Navigation("OriginFlightNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.BaggageType", b =>
                {
                    b.Navigation("BaggageReservationNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.CancellationReason", b =>
                {
                    b.Navigation("PurchaseCancellationNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Country", b =>
                {
                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("PassengerNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Flight", b =>
                {
                    b.Navigation("FlightDetailsNavigation");

                    b.Navigation("FlightPromotionsNavigation");

                    b.Navigation("OperationalCostsNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.FlightDetail", b =>
                {
                    b.Navigation("BaggageReservationNavigation");

                    b.Navigation("InvoiceDetailNavigation");

                    b.Navigation("SeatReservationNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetailNavigation");

                    b.Navigation("InvoicePaymentNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.InvoiceDetail", b =>
                {
                    b.Navigation("PurchaseCancellationNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Passenger", b =>
                {
                    b.Navigation("FlightDetailsNavigation");

                    b.Navigation("InvoiceNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PassengerType", b =>
                {
                    b.Navigation("PassengersNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("InvoicePaymentNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("FlightPromotionsNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.SeatType", b =>
                {
                    b.Navigation("SeatReservationNavigation");
                });

            modelBuilder.Entity("AirLineMetrics.Domain.Entities.State", b =>
                {
                    b.Navigation("AiportsNavigation");

                    b.Navigation("FlightNavigation");

                    b.Navigation("PassengersNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
